# Generated by Django 6.0.2 on 2026-02-18 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('market', 'Market Size & Opportunity'), ('competition', 'Competition & Differentiation'), ('business_model', 'Business Model & Revenue'), ('team', 'Team & Execution'), ('traction', 'Traction & Metrics'), ('financials', 'Financials & Projections'), ('product', 'Product & Technology'), ('risks', 'Risks & Challenges')], db_index=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=20)),
                ('related_slide_number', models.IntegerField(blank=True, null=True)),
                ('key_points_to_cover', models.JSONField(blank=True, default=list)),
                ('times_asked', models.IntegerField(default=0)),
                ('average_answer_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pitch_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pitches.pitchdeck')),
            ],
            options={
                'verbose_name': 'Investor Question',
                'verbose_name_plural': 'Investor Questions',
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('answer_duration_seconds', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(db_index=True, default=0)),
                ('completeness_score', models.FloatField(default=0)),
                ('clarity_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('relevance_score', models.FloatField(default=0)),
                ('key_points_covered', models.JSONField(blank=True, default=list)),
                ('key_points_missed', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('strong_points', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('suggested_answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('practice_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_answers', to='practice.practicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.question')),
            ],
            options={
                'verbose_name': 'Q&A Answer',
                'verbose_name_plural': 'Q&A Answers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['pitch_deck', 'category'], name='qa_question_pitch_d_e82a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'times_asked'], name='qa_question_difficu_f794d2_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', '-created_at'], name='qa_answer_user_id_6d4fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', '-quality_score'], name='qa_answer_questio_9f99e8_idx'),
        ),
    ]
