# Generated by Django 6.0.2 on 2026-02-18 01:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('uploaded_file', models.FileField(max_length=500, upload_to='pitch_decks/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx', 'ppt'])])),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_slides', models.IntegerField(default=0)),
                ('analyzed', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pitch Deck',
                'verbose_name_plural': 'Pitch Decks',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slide_number', models.IntegerField(db_index=True)),
                ('text_content', models.TextField(blank=True)),
                ('has_images', models.BooleanField(default=False)),
                ('has_charts', models.BooleanField(default=False)),
                ('slide_type', models.CharField(blank=True, choices=[('title', 'Title/Cover'), ('problem', 'Problem Statement'), ('solution', 'Solution'), ('product', 'Product Demo'), ('market', 'Market Size'), ('business_model', 'Business Model'), ('traction', 'Traction/Metrics'), ('competition', 'Competition'), ('team', 'Team'), ('financials', 'Financials'), ('ask', 'The Ask'), ('other', 'Other')], db_index=True, max_length=50)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('suggestions', models.TextField(blank=True)),
                ('suggested_script', models.TextField(blank=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('estimated_speaking_time', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='pitches.pitchdeck')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['slide_number'],
            },
        ),
        migrations.AddIndex(
            model_name='pitchdeck',
            index=models.Index(fields=['-uploaded_at', 'owner'], name='pitches_pit_uploade_94abe8_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchdeck',
            index=models.Index(fields=['status', 'analyzed'], name='pitches_pit_status_bfce62_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['pitch_deck', 'slide_number'], name='pitches_sli_pitch_d_c62448_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['slide_type', 'quality_score'], name='pitches_sli_slide_t_2190ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('pitch_deck', 'slide_number')},
        ),
    ]
