# Generated by Django 6.0.2 on 2026-02-18 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('pitch_decks_limit', models.IntegerField(default=3)),
                ('practice_sessions_limit', models.IntegerField(default=10)),
                ('pitch_decks_uploaded', models.IntegerField(default=0)),
                ('practice_sessions_completed', models.IntegerField(default=0)),
                ('total_practice_time_seconds', models.BigIntegerField(default=0)),
                ('preferred_pitch_type', models.CharField(blank=True, max_length=50)),
                ('target_practice_duration', models.IntegerField(default=300)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('average_practice_score', models.FloatField(default=0)),
                ('best_practice_score', models.FloatField(default=0)),
                ('improvement_rate', models.FloatField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['subscription_tier', '-created_at'], name='accounts_us_subscri_d02c1b_idx'), models.Index(fields=['user', 'subscription_tier'], name='accounts_us_user_id_d10f23_idx')],
            },
        ),
    ]
