# Generated by Django 6.0.2 on 2026-02-18 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('first_session_date', models.DateTimeField(blank=True, null=True)),
                ('last_session_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to='pitches.pitchdeck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Progress',
                'verbose_name_plural': 'Practice Progress',
                'unique_together': {('user', 'pitch_deck')},
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch_type', models.CharField(choices=[('elevator', 'Elevator Pitch (30 seconds)'), ('demo_day', 'Demo Day (3 minutes)'), ('investor', 'Investor Pitch (10 minutes)'), ('competition', 'Competition Pitch (5 minutes)')], db_index=True, max_length=50)),
                ('session_number', models.IntegerField(default=1)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('target_duration_seconds', models.IntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('word_count', models.IntegerField(db_index=True, default=0)),
                ('overall_score', models.FloatField(db_index=True, default=0)),
                ('pace_score', models.FloatField(default=0)),
                ('clarity_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('content_score', models.FloatField(default=0)),
                ('structure_score', models.FloatField(default=0)),
                ('speaking_pace_wpm', models.FloatField(default=0)),
                ('filler_words_count', models.IntegerField(default=0)),
                ('unique_words_count', models.IntegerField(default=0)),
                ('filler_words_detail', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pitch_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='pitches.pitchdeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Session',
                'verbose_name_plural': 'Practice Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_pr_user_id_b1e8c7_idx'), models.Index(fields=['pitch_deck', '-overall_score'], name='practice_pr_pitch_d_022d57_idx'), models.Index(fields=['pitch_type', '-created_at'], name='practice_pr_pitch_t_e92d47_idx')],
            },
        ),
    ]
